version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_DATABASE="${DB_NAME}"
    ports:
      - 27017:27017
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=${DB_SERVER}
      - ME_CONFIG_MONGODB_PORT=${DB_PORT}
    depends_on:
      - mongo
    ports:
      - 8081:8081

    
